// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeZuw3ABYp82U0v03KcU005-1-PnkB-ZI',
    appId: '1:162049479093:web:779dba39f3359051549fc',
    messagingSenderId: '162049479093',
    projectId: 'loopcode-25d90',
    authDomain: 'loopcode-25d90.firebaseapp.com',
    databaseURL: 'https://loopcode-25d90-default-rtdb.firebaseio.com',
    storageBucket: 'loopcode-25d90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeZuw3ABYp82U0v03KcU005-1-PnkB-ZI',
    appId: '1:162049479093:android:ff577728fec18cf5489fc',
    messagingSenderId: '162049479093',
    projectId: 'loopcode-25d90',
    databaseURL: 'https://loopcode-25d90-default-rtdb.firebaseio.com',
    storageBucket: 'loopcode-25d90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeZuw3ABYp82U0v03KcU005-1-PnkB-ZI',
    appId: '1:162049479093:ios:575cb0461e71a9515489fc',
    messagingSenderId: '162049479093',
    projectId: 'loopcode-25d90',
    databaseURL: 'https://loopcode-25d90-default-rtdb.firebaseio.com',
    storageBucket: 'loopcode-25d90.appspot.com',
    iosBundleId: 'com.example.loopcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeZuw3ABYp82U0v03KcU005-1-PnkB-ZI',
    appId: '1:162049479093:ios:575cb0461e71a9515489fc',
    messagingSenderId: '162049479093',
    projectId: 'loopcode-25d90',
    databaseURL: 'https://loopcode-25d90-default-rtdb.firebaseio.com',
    storageBucket: 'loopcode-25d90.appspot.com',
    iosBundleId: 'com.example.loopcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeZuw3ABYp82U0v03KcU005-1-PnkB-ZI',
    appId: '1:162049479093:web:81de0dd42872d2145489fc',
    messagingSenderId: '162049479093',
    projectId: 'loopcode-25d90',
    authDomain: 'loopcode-25d90.firebaseapp.com',
    databaseURL: 'https://loopcode-25d90-default-rtdb.firebaseio.com',
    storageBucket: 'loopcode-25d90.appspot.com',
  );
}
